footprint: [[-0.25, -0.19], [-0.25, 0.19], [0.1, 0.19], [0.1, -0.19]]

footprint_padding: 0.03

robot_base_frame: base_footprint
update_frequency: 2
publish_frequency: 2
transform_tolerance: 2

resolution: 0.1 #default 0.05

obstacle_range: 2 #default 3
raytrace_range: 2.5 #default 4


#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan, inf_is_valid: true}

# obstacles_pointcloud:
#     observation_sources: point_cloud_sensor
#     point_cloud_sensor: {sensor_frame: map, data_type: PointCloud2, topic: /camera/depth/color/points , marking: true, clearing: true}
#     max_obstacle_height: 0.35
#     min_obstacle_height: 0.1
    
inflation_g:
    inflation_radius: 0.06 #default 0.055
    
inflation_l:
    inflation_radius: 0.06 #default 0.055