

footprint: [[-0.155, -0.155], [-0.155, 0.155], [0.155, 0.155], [0.155, -0.155]]
footprint_padding: 0.0

transform_tolerance: 2

# Define each layer here ....

static:
    enabled: true
    map_topic: map
    # Whether or not the costmap initialize itself based on a map serverd by the map_server
    #static_map: true


sensor_obstacle:
    enabled: true

    obstacle_range: 4
    raytrace_range: 5
    track_unknown_space: false
    #Observation_sources <--> define a list of sensors going to pass infomation to costmap
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: base_laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

inflation:
    enabled: true

    inflation_radius: 0.0
    cost_scaling_factor: 0.0