# Choose which Global Planner Plugin to use
base_global_planner: navfn/NavfnROS
# Choose which Local Planner Plugin to use
base_local_planner: teb_local_planner/TebLocalPlannerROS

controller_frequency: 10.0
controller_patience: 2.0

planner_frequency: 2
planner_patience: 2.0

oscillation_timeout: 0.0
oscillation_distance: 0.2

shutdown_costmap: false

recovery_behavior_enabled: true
conservative_reset_dist: 0.1

clearing_rotation_allowed: false
